# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f469e886a4825af8cc4b94d079959f9afc43b53590bcac634e93e118215d21b787eecb8557bdc86fa46a8d5ae26d126c68deb8ade0d27e5a151c2fe8cbca6f9

test:
  secret_key_base: ef371cd08f9e740d8a023f0ca3171114df59968191cf688b162f7a29a6f98d0b41a003e7915c7c26a48d9a88e898e1e6a101e14b21b157c531a8a224af30ec8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
